FROM node:16-alpine as build

WORKDIR /app/client

COPY package.json .

RUN  npm install --silent

COPY . .

RUN npm run build


FROM nginx:stable-alpine

COPY --from=build /app/client/docs /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
