FROM node:16-alpine as build

WORKDIR /app/client

COPY . .

RUN  npm install --silent

CMD ["npm", "run", "start"]

# RUN npm run build

# FROM node:16-alpine

# WORKDIR /app/client

# RUN npm install -g serve

# COPY --from=build  /app/client/docs /app/client/docs

# CMD ["serve", "-s", "docs"]
